site_name: AIO Azure Clients Toolbox
site_description: Async Python connection pooling library for Azure SDK clients
site_url: https://mulliganfunding.github.io/aio-azure-clients-toolbox/
repo_url: https://github.com/MulliganFunding/aio-azure-clients-toolbox
repo_name: MulliganFunding/aio-azure-clients-toolbox
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Installation: installation.md
  - Connection Pooling: connection-pooling.md
  - Clients:
    - Azure Blobs: clients/azure-blobs.md
    - Cosmos DB: clients/cosmos.md
    - Event Grid: clients/eventgrid.md
    - Event Hub: clients/eventhub.md
    - Service Bus: clients/service-bus.md
  - Testing:
    - Fixtures: testing/fixtures.md
    - Examples: testing/examples.md
  - Advanced:
    - Custom Clients: advanced/custom-clients.md
    - Configuration: advanced/configuration.md
    - Troubleshooting: advanced/troubleshooting.md
  - API Reference:
    - Connection Pooling: api-reference/connection-pooling.md
    - Clients: api-reference/clients.md
    - Testing Utils: api-reference/testing-utils.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MulliganFunding/aio-azure-clients-toolbox
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/aio-azure-clients-toolbox/

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/mermaid.js

extra_css:
  - stylesheets/mermaid.css