name: Release
on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    name: Build and publish aio-azure-clients-toolbox to PyPi
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    environment:
      name: PyPi
      url: https://pypi.org/p/aio-azure-clients-toolbox
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - name: Install pypa/build
        run: just build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
